import assert from "node:assert/strict";
import test from "node:test";
import { buildXlsxFile } from "../frontend/services/xlsx-writer.ts";
import {
  autoDetectColumnMapping,
  parseCsvText,
  parseImportAmount,
  parseXlsxBuffer,
  prepareImportPreview,
} from "../frontend/services/excel-csv-import.service.ts";

test("parseCsvText handles quotes, commas, and Vietnamese Unicode with BOM", () => {
  const csvContent = '\uFEFF"Ngày","Tiêu đề","Số tiền","Loại"\n"2026-09-15","Ăn trưa, phở bò","55000","Chi tiêu"\n"2026-09-16","Cà phê ""Highlands""","39000","Chi tiêu"';
  const rows = parseCsvText(csvContent);

  assert.equal(rows.length, 3);
  assert.deepEqual(rows[0], ["Ngày", "Tiêu đề", "Số tiền", "Loại"]);
  assert.equal(rows[1][1], "Ăn trưa, phở bò");
  assert.equal(rows[2][1], 'Cà phê "Highlands"');
});

test("parseXlsxBuffer parses workbook generated by buildXlsxFile", () => {
  const xlsxBytes = buildXlsxFile([
    {
      name: "GiaoDich",
      rows: [
        { "Ngày": "2026-09-15", "Tiêu đề": "Lương tháng 9", "Số tiền": 15000000, "Loại": "Thu" },
      ],
    },
  ]);

  const rows = parseXlsxBuffer(xlsxBytes);
  assert.ok(rows.length >= 2);
  assert.equal(rows[0][0], "Ngày");
  assert.equal(rows[1][1], "Lương tháng 9");
  assert.equal(rows[1][2], "15000000");
});

test("autoDetectColumnMapping detects Vietnamese and English headers", () => {
  const mappingVi = autoDetectColumnMapping(["Ngày giao dịch", "Tên khoản chi", "Số tiền", "Danh mục", "Ví"]);
  assert.equal(mappingVi.dateColumn, "Ngày giao dịch");
  assert.equal(mappingVi.titleColumn, "Tên khoản chi");
  assert.equal(mappingVi.amountColumn, "Số tiền");
  assert.equal(mappingVi.categoryColumn, "Danh mục");
  assert.equal(mappingVi.walletColumn, "Ví");

  const mappingEn = autoDetectColumnMapping(["Date", "Description", "Amount", "Category", "Account"]);
  assert.equal(mappingEn.dateColumn, "Date");
  assert.equal(mappingEn.titleColumn, "Description");
  assert.equal(mappingEn.amountColumn, "Amount");
});

test("parseImportAmount handles Vietnamese dot and comma currency formats", () => {
  assert.equal(parseImportAmount("1.500.000 ₫"), 1500000);
  assert.equal(parseImportAmount("45,000 VND"), 45000);
  assert.equal(parseImportAmount("350.000"), 350000);
  assert.equal(parseImportAmount("1,250.50"), 1250.5);
  assert.equal(parseImportAmount("invalid"), null);
});

test("prepareImportPreview accurately categorizes valid, invalid, and duplicate rows", () => {
  const headers = ["Ngày", "Tiêu đề", "Số tiền", "Loại", "Danh mục", "Ví"];
  const rows = [
    headers,
    ["2026-09-15", "Ăn sáng bánh mì", "25000", "Chi", "Ăn uống", "Ví tiền mặt"],
    ["2026-09-15", "Giao dịch thiếu tiền", "0", "Chi", "Ăn uống", "Ví tiền mặt"], // invalid
    ["2026-09-15", "Ăn trưa cơm tấm", "45000", "Chi", "Ăn uống", "Ví tiền mặt"], // duplicate
  ];

  const categories = [{ id: "cat-1", name: "Ăn uống", kind: "expense" }];
  const wallets = [{ id: "w-1", name: "Ví tiền mặt", type: "cash" }];
  const existingTransactions = [
    {
      id: "tx-exist",
      title: "Ăn trưa cơm tấm",
      amount: 45000,
      type: "expense",
      wallet_id: "w-1",
      occurred_at: "2026-09-15T12:00:00.000Z",
    },
  ];

  const mapping = autoDetectColumnMapping(headers);
  const previews = prepareImportPreview({
    rows,
    mapping,
    categories,
    wallets,
    existingTransactions,
  });

  assert.equal(previews.length, 3);
  assert.equal(previews[0].status, "valid");
  assert.equal(previews[1].status, "invalid");
  assert.equal(previews[2].status, "duplicate");
});
